//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormium.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormium.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 var chrome;
        ///var formium;
        ///
        ///(function ($window) {
        ///    const WEB_VIEW_LISTENERS = {};
        ///    chrome = $window.chrome || {};
        ///
        ///    class WebView {
        ///
        ///        emitWebMessage(type, asString, data) {
        ///            try {
        ///
        ///                let retval = data;
        ///                if (asString === false) {
        ///                    try {
        ///                        retval = JSON.parse(data);
        ///                    }
        ///                    catch {
        ///
        ///                    }
        ///                }
        ///                const event = new Event( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string formium_js {
            get {
                return ResourceManager.GetString("formium.js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(n){class t{constructor(){this._isMaximized=!1;this._isMinimized=!1;this._isFullScreen=!1}maximize(){this._isMaximized=!0;console.log(&quot;Window maximized&quot;)}minimize(){this._isMinimized=!0;console.log(&quot;Window minimized&quot;)}restore(){this._isMaximized=!1;this._isMinimized=!1;console.log(&quot;Window restored&quot;)}close(){console.log(&quot;Window closed&quot;)}fullScreen(){this._isFullScreen=!0;console.log(&quot;Window in full screen mode&quot;)}exitFullScreen(){this._isFullScreen=!1;console.log(&quot;Exited full screen mode&quot;)}}Object.de [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string hostwindow_js {
            get {
                return ResourceManager.GetString("hostwindow.js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (function(){function t(){const t=&quot;font-size:0.8em;background: #35495e; padding: 4px; border-radius: 5px 0 0 5px; color: #fff&quot;,i=&quot;font-size:0.8em;background: #83b841; padding: 4px; border-radius: 0 5px 5px 0; color: #fff&quot;;console.log(`==== Welcome to the%c WinFormium %cProject ====`,&quot;color: #fff;font-weight:bold;font-size:1.1em;text-shadow: #152173 0 0 3px;&quot;,&quot;&quot;);console.log(n,t,i,&quot;&quot;,t,i,&quot;&quot;,t,i,&quot;&quot;);console.log(`Copyrights (C) ${(new Date).getFullYear()} Xuanchen Lin all rights reserved.`)}const n=`{{WINFORMIU [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string version_js {
            get {
                return ResourceManager.GetString("version.js", resourceCulture);
            }
        }
    }
}
