name: Build and Publish

on:
  push:
    branches: [master]

jobs:

  build:
    permissions:
      id-token: write
      contents: read
      
    runs-on: windows-latest
    environment: production

    env:
      Solution_Name: "WinFormiumProject.sln"

    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Get .NET information
        run: dotnet --info

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Clean .NET cache
        id: clean_dotnet_cache
        shell: pwsh
        run: |
          dotnet clean $env:Solution_Name
          dotnet nuget locals all --clear

      - name: Install NuGet packages
        id: install_nuget_packages
        shell: pwsh
        run: |
          nuget restore $env:Solution_Name

      - name: Build solution
        id: build_solution
        shell: pwsh
        run: |
          msbuild $env:Solution_Name -property:Configuration=Release

      - name: Install Nuget
        run: |
          $sourceNugetExe = "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe"
          $targetNugetExe = "nuget.exe"
          Invoke-WebRequest $sourceNugetExe -OutFile $targetNugetExe

      - name: Nuget Authorization (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push Nuget package
        run: |
          .\nuget.exe push .\bin\*.nupkg -ApiKey ${{steps.login.outputs.NUGET_API_KEY}} -NoSymbols -SkipDuplicate -Source https://api.nuget.org/v3/index.json
          .\nuget.exe push .\bin\*.snupkg -ApiKey ${{steps.login.outputs.NUGET_API_KEY}} -SkipDuplicate -Source https://api.nuget.org/v3/index.json
